 
<div class="" id='MallCustomerService'>
<?php 


$qq=urlencode(Mage::getStoreConfig('livechat/livechat/qq'));
$wangwang=urlencode(Mage::getStoreConfig('livechat/livechat/wangwang'));
if(isset($qq)){
?>

<a class=""  target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=<?php echo $qq; ?>&site=qq&menu=yes"><img border="0" src="http://wpa.qq.com/pa?p=2:<?php echo $qq; ?>:52" alt="点击这里给我发消息" title="点击这里给我发消息"/></a>
<?php
}
?>

<?php
if(isset($qq)){
?>

<a class=""  target="_blank" href="http://www.taobao.com/webww/ww.php?ver=3&touid=<?php echo $wangwang; ?>&siteid=cntaobao&status=2&charset=utf-8"><img border="0" src="http://amos.alicdn.com/realonline.aw?v=2&uid=<?php echo $wangwang; ?>&site=cntaobao&s=2&charset=utf-8" alt="点击这里给我发消息" /></a>

<?php
}
?>



</div> 
